[log]
  level = "ERROR"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    network = "traefik_proxy"
    watch = true
    exposedbydefault = false

[accessLog]

[api]
  dashboard = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.http.auth.forward]
    address = "http://traefik-forward-auth:4181"
    authResponseHeaders = ["X-Forwarded-User"]
  [entryPoints.https]
    address = ":443"
  [entryPoints.ping]
    address = ":8082"

[ping]
  entryPoint = "ping"

[certificatesResolvers]
  [certificatesResolvers.myresolver.acme]
    email = "kirintw@kirintw.app"
    storage = "/etc/traefik/ACME/acme.json"
    [certificatesResolvers.myresolver.acme.tlsChallenge]
